name: mobile_assessment
description: Irecharge mobile team assessment

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts:
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable:
  build_runner:

#flutter_icons:
#  ios: true
#  android: true
#  image_path_ios: 'assets/images/logo_transparent.png'
#  image_path_android: 'assets/images/logo_transparent.png'

flutter:

  uses-material-design: true

  # assets:
  #   - assets/responses/
